//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautyDesktopApp.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BeautyBaseEntities : DbContext
    {
        public BeautyBaseEntities()
            : base("name=BeautyBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Должность> Должность { get; set; }
        public virtual DbSet<Запись_на_услугу> Запись_на_услугу { get; set; }
        public virtual DbSet<Клиент> Клиент { get; set; }
        public virtual DbSet<Работник> Работник { get; set; }
        public virtual DbSet<Услуга> Услуга { get; set; }
    }
}
