//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautyDesktopApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Отзыв
    {
        public int ID_отзыва { get; set; }
        public int ID_клиента { get; set; }
        public string Текст { get; set; }
        public System.DateTime Дата_публикации { get; set; }
    
        public virtual Клиент Клиент { get; set; }
    }
}
